apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: auth
spec:
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: web-application
  requiredAuthenticationRefs:
    - name: client
      kind: ServiceAccount
      namespace: <YOURNAME>-client # <-- please adjust <YOURNAME>
