apiVersion: v1
kind: Service
metadata:
  labels:
    app: metrics-app-service
  name: metrics-app-service
spec:
  ports:
  - port: 8090
    targetPort: 8090
    protocol: TCP
  selector:
    app: metrics-app
  type: LoadBalancer
