resources:
  requests:
    memory: 256Mi
  limits:
    memory: 256Mi
serviceMonitor:
  enabled: true
tolerations:
  - effect: NoSchedule
    operator: Exists
config:
  clients:
    - url: 'http://loki:3100/loki/api/v1/push'
  snippets:
    extraScrapeConfigs: |
      - job_name: journal
        journal:
          path: /var/log/journal
          max_age: 12h
          labels:
            job: systemd-journal
        relabel_configs:
          - source_labels: ['__journal__systemd_unit']
            target_label: 'unit'
          - source_labels: ['__journal__hostname']
            target_label: 'hostname'
extraVolumes:
  - name: journal
    hostPath:
      path: /var/log/journal
extraVolumeMounts:
  - name: journal
    mountPath: /var/log/journal
    readOnly: true

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 25%
