apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: workshop-tls-cert
  namespace: ingress-nginx
spec:
  commonName: '*.workshop.metakube.org'
  dnsNames:
    - '*.workshop.metakube.org'
  secretName: workshop-tls-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
