# deploy prometheus
prometheus:
  prometheusSpec:
    retention: 24h
    ruleSelector: {}
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    replicas: 2
    podAntiAffinity: hard
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: sys11-quobyte-external-provisioner
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
  # now we enable an ingress resource to make prometheus web interface publically available
  # under a DNS name secured by a certificate and basic authentication
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      kubernetes.io/ingress.class: nginx
    hosts:
      - prometheus.workshop.metakube.org
    tls:
      - hosts:
          - prometheus.workshop.metakube.org

# deploy grafana
grafana:
  nodeSelector:
    grafana: "true"
  replicas: 1
  adminPassword: admin
  persistence:
    enabled: true
  ingress:
    # enable grafana public ingress
    enabled: true
    annotations:
      ## optionally enable basic auth as for prometheus web interface
      # nginx.ingress.kubernetes.io/auth-type: basic
      # nginx.ingress.kubernetes.io/auth-secret: basic-auth
      kubernetes.io/ingress.class: nginx
    hosts:
      - grafana.workshop.metakube.org
    tls:
      - hosts:
          - grafana.workshop.metakube.org
  # "classic" grafana configuration
  grafana.ini:
    server:
      root_url: https://grafana.workshop.metakube.org
      server_domain: https://grafana.workshop.metakube.org
    auth:
      signout_redirect_url: https://keycloak.metakube.org/auth/realms/observability/protocol/openid-connect/logout?redirect_uri=https%3A%2F%2Fgrafana.workshop.metakube.org%2Flogin
    auth.generic_oauth:
      enabled: true
      allow_sign_up: true
      basic_enabled: false
      # disable_login_form: true
      anonymous_enabled: false
      disable_signout_menu: false
      api_url: https://keycloak.metakube.org/auth/realms/observability/protocol/openid-connect/userinfo
      auth_url: https://keycloak.metakube.org/auth/realms/observability/protocol/openid-connect/auth
      token_url: https://keycloak.metakube.org/auth/realms/observability/protocol/openid-connect/token
      client_id: grafana
      client_secret: XXXXXXXXXXXXXXXXXXXXXXXX # <-- please adjust
      name: KeyCloak Observability Realm
      role_attribute_path: contains(roles[*], 'grafana-admin') && 'Admin' || contains(roles[*], 'grafana-editor') && 'Editor' || 'Viewer'
      scopes: openid profile email
      empty_scopes: false
      auto_login: false
      server_serve_from_sub_path: true
    users:
      auto_assign_org_role: Admin
    analytics:
      check_for_updates: false
  # make grafana notice new dashboards for import at runtime
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
    datasources:
      enabled: true
      label: grafana_datasource

# deploy alertmanager
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    replicas: 2
    podAntiAffinity: hard

# monitor kubernetes components
defaultRules:
  rules:
    kubernetesResources: true

# monitor the kubelet on worker nodes
kubelet:
  enabled: true
  namespace: kube-system
  serviceMonitor:
    https: true

# monitor coreDNS service
coreDns:
  enabled: true
  service:
    port: 9153
    targetPort: 9153
    selector:
      app: coredns
      app.kubernetes.io/name: kube-dns

# monitor the kubernetes database - etcd key values store
kubeEtcd:
  enabled: true

# we do not need these because the kube-controller-manager and kube-scheduler
# are managed and monitored by MetaKube itself
kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false
